# @TodoApi_HostAddress = http://localhost:5059

# GET {{TodoApi_HostAddress}}/weatherforecast/
# Accept: application/json


###

# Simple get
# Select request / command
# and press Command + Shift + P: Rest Client: Send Request
GET http://localhost:5059/api/todoitems
GET http://localhost:5059/weatherforecast
GET http://localhost:5059/swagger




# Simple post
POST http://localhost:5059/api/todoitems
Content-Type: application/json

{
    "name": "muista hedelmiä"
} 